check: support/homebrew-container check "$@"
#? Check all formulae in clean Homebrew containers
#$ [FORMULA...]

outdated: support/homebrew-container outdated
#? Show formulae with newer upstream releases

update: support/homebrew-container update "$@"
#? Update a formula to a new upstream version
#$ FORMULA VERSION

shell: support/homebrew-container shell
#? Open a Homebrew container with this tap mounted

pristine: support/homebrew-container shell --pristine
#? Open an unmounted pristine Homebrew container
